# Generated by Django 3.2.6 on 2021-08-06 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'To Do List', 'verbose_name_plural': 'To Do Lists'},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='due_date',
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('created', models.DateField(default=datetime.datetime(2021, 8, 6, 12, 44, 20, 796701, tzinfo=utc))),
                ('due_date', models.DateField(default=datetime.datetime(2021, 8, 6, 12, 44, 20, 796701, tzinfo=utc))),
                ('to_do_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todolist')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created'],
            },
        ),
    ]
