# Generated by Django 3.2.6 on 2021-08-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_order_orders_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.customers'),
        ),
    ]
