# Generated by Django 3.2.6 on 2021-08-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subscriptions_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='customer',
        ),
        migrations.AddField(
            model_name='customers',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subscriptions'),
        ),
    ]
