# Generated by Django 3.2.7 on 2021-09-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_orders_modified_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackingListActive',
            new_name='PackingLists',
        ),
        migrations.RemoveField(
            model_name='packinglistholidays',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='PackingListHolidays',
        ),
    ]
