# Generated by Django 3.2.7 on 2021-09-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210906_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='week_end',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='week_start',
            field=models.DateField(editable=False, null=True),
        ),
    ]
