# Generated by Django 3.2.6 on 2021-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_orders_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
