# Generated by Django 3.2.7 on 2021-09-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210901_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='week_end',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='week_start',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('subscription', 'week_start', 'week_end')},
        ),
    ]
