# Generated by Django 3.2.7 on 2021-09-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210902_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
