# Generated by Django 3.2.7 on 2021-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210904_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('subscription', 'week_start', 'week_end')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['id', 'cost'], name='api_subscri_id_2e4eb3_idx'),
        ),
    ]
