# Generated by Django 3.2.7 on 2021-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210906_1627'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='api_subscri_id_2e4eb3_idx',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
    ]
